### ISSUE TITLE
UserWarning: Subprocess mineflayer failed to start.raise ConnectionError(err, request=request) requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine('SSH-2.0-OpenSSH_8.2p1 Ubuntu-4ubuntu0.5\r\n'))

### ISSUE THREAD

**Issue by OrilinZ** [MineDojo/Voyager#106]
When I run Voyager, I always meet with the timeout problem. What can I do?

When I `python run_skill.py `

run_skill.py:
```
voyager = Voyager(
    # azure_login=azure_login,
    mc_port=mc_port,
    openai_api_key=openai_api_key,
    openai_api_base=openai_api_base,
    skill_library_dir="./skill_library/trial1", # Load a learned skill library.
    ckpt_dir="./skill_library/trial_n1", # Feel free to use a new dir. Do not use the same dir as skill library because new events will still be recorded to ckpt_dir. 
    resume=False, # Do not resume from a skill library because this is not learning.
)

# task = "Craft an iron pickaxe" # e.g.
# sub_goals = voyager.decompose_task(task=task)
# voyager.inference(sub_goals=sub_goals)
voyager.learn()
```

I got:
```
Loading Skill Manager from ./skill_library/trial1/skill
Mineflayer process has exited, restarting
Subprocess mineflayer started with PID 2743659.
/data/zhz_data/Voyager/voyager/env/process_monitor.py:65: UserWarning: Subprocess mineflayer failed to start.
  warnings.warn(f"Subprocess {self.name} failed to start.")
None
```

```
2023-07-06 19:41:50,088 - mineflayer - INFO - Stopping subprocess.
2023-07-06 19:41:51,090 - mineflayer - INFO - Starting subprocess with commands: ['node', '/data/zhz_data/Voyager/voyager/env/mineflayer/index.js', '6010']
2023-07-06 19:41:51,456 - mineflayer - INFO - node:events:491
2023-07-06 19:41:51,457 - mineflayer - INFO - throw er; // Unhandled 'error' event
2023-07-06 19:41:51,458 - mineflayer - INFO - ^
2023-07-06 19:41:51,458 - mineflayer - INFO - 
2023-07-06 19:41:51,458 - mineflayer - INFO - Error: listen EADDRINUSE: address already in use :::6010
2023-07-06 19:41:51,458 - mineflayer - INFO - at Server.setupListenHandle [as _listen2] (node:net:1740:16)
2023-07-06 19:41:51,458 - mineflayer - INFO - at listenInCluster (node:net:1788:12)
2023-07-06 19:41:51,458 - mineflayer - INFO - at Server.listen (node:net:1876:7)
2023-07-06 19:41:51,458 - mineflayer - INFO - at Function.listen (/data/zhz_data/Voyager/voyager/env/mineflayer/node_modules/express/lib/application.js:635:24)
2023-07-06 19:41:51,458 - mineflayer - INFO - at Object.<anonymous> (/data/zhz_data/Voyager/voyager/env/mineflayer/index.js:423:5)
2023-07-06 19:41:51,458 - mineflayer - INFO - at Module._compile (node:internal/modules/cjs/loader:1256:14)
2023-07-06 19:41:51,458 - mineflayer - INFO - at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
2023-07-06 19:41:51,458 - mineflayer - INFO - at Module.load (node:internal/modules/cjs/loader:1119:32)
2023-07-06 19:41:51,458 - mineflayer - INFO - at Module._load (node:internal/modules/cjs/loader:960:12)
2023-07-06 19:41:51,458 - mineflayer - INFO - at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
2023-07-06 19:41:51,458 - mineflayer - INFO - Emitted 'error' event on Server instance at:
2023-07-06 19:41:51,458 - mineflayer - INFO - at emitErrorNT (node:net:1767:8)
2023-07-06 19:41:51,458 - mineflayer - INFO - at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
2023-07-06 19:41:51,458 - mineflayer - INFO - code: 'EADDRINUSE',
2023-07-06 19:41:51,458 - mineflayer - INFO - errno: -98,
2023-07-06 19:41:51,458 - mineflayer - INFO - syscall: 'listen',
2023-07-06 19:41:51,458 - mineflayer - INFO - address: '::',
2023-07-06 19:41:51,458 - mineflayer - INFO - port: 6010
2023-07-06 19:41:51,458 - mineflayer - INFO - }
2023-07-06 19:41:51,458 - mineflayer - INFO - 
2023-07-06 19:41:51,458 - mineflayer - INFO - Node.js v18.16.1
```

**Comment by air-balls** [comment]
I have met the same issue, could you please tell me how to solve the problem?
