### ISSUE TITLE
THREE.WebGLRenderer: Cannot read properties of null (reading 'getUniformLocation')

### ISSUE THREAD

**Issue by OrilinZ** [MineDojo/Voyager#114]
```
2023-07-21 18:59:34,161 - mineflayer - INFO - Stopping subprocess.
2023-07-21 18:59:35,163 - mineflayer - INFO - Starting subprocess with commands: ['node', '/data/zhz_data/Voyager/voyager/env/mineflayer/index.js', '3001']
2023-07-21 18:59:35,574 - mineflayer - INFO - Server started on port 3001
2023-07-21 18:59:35,575 - mineflayer - INFO - Subprocess is ready.
2023-07-21 18:59:35,588 - mineflayer - INFO - {
2023-07-21 18:59:35,588 - mineflayer - INFO - port: 35071,
2023-07-21 18:59:35,588 - mineflayer - INFO - reset: 'hard',
2023-07-21 18:59:35,588 - mineflayer - INFO - inventory: {},
2023-07-21 18:59:35,588 - mineflayer - INFO - equipment: [],
2023-07-21 18:59:35,588 - mineflayer - INFO - spread: false,
2023-07-21 18:59:35,588 - mineflayer - INFO - waitTicks: 20,
2023-07-21 18:59:35,588 - mineflayer - INFO - position: null
2023-07-21 18:59:35,588 - mineflayer - INFO - }
2023-07-21 18:59:38,086 - mineflayer - INFO - THREE.WebGLRenderer: Cannot read properties of null (reading 'getUniformLocation')
2023-07-21 18:59:38,090 - mineflayer - INFO - /data/zhz_data/Voyager/node-canvas-webgl/lib/canvas.js:88
2023-07-21 18:59:38,090 - mineflayer - INFO - const _getUniformLocation = ctx.getUniformLocation;
2023-07-21 18:59:38,090 - mineflayer - INFO - ^
2023-07-21 18:59:38,090 - mineflayer - INFO - 
2023-07-21 18:59:38,090 - mineflayer - INFO - TypeError: Cannot read properties of null (reading 'getUniformLocation')
2023-07-21 18:59:38,090 - mineflayer - INFO - at NodeCanvasElement.getContext (/data/zhz_data/Voyager/node-canvas-webgl/lib/canvas.js:88:39)
2023-07-21 18:59:38,090 - mineflayer - INFO - at getContext (/data/zhz_data/Voyager/voyager/env/mineflayer/node_modules/three/build/three.js:17304:29)
2023-07-21 18:59:38,090 - mineflayer - INFO - at new WebGLRenderer (/data/zhz_data/Voyager/voyager/env/mineflayer/node_modules/three/build/three.js:17335:11)
2023-07-21 18:59:38,090 - mineflayer - INFO - at module.exports (/data/zhz_data/Voyager/voyager/env/mineflayer/node_modules/prismarine-viewer/lib/headless.js:19:20)
2023-07-21 18:59:38,090 - mineflayer - INFO - at EventEmitter.<anonymous> (/data/zhz_data/Voyager/voyager/env/mineflayer/index.js:56:9)
2023-07-21 18:59:38,090 - mineflayer - INFO - at Object.onceWrapper (node:events:627:28)
2023-07-21 18:59:38,090 - mineflayer - INFO - at EventEmitter.emit (node:events:525:35)
2023-07-21 18:59:38,090 - mineflayer - INFO - at Client.<anonymous> (/data/zhz_data/Voyager/voyager/env/mineflayer/node_modules/mineflayer/lib/plugins/health.js:13:11)
2023-07-21 18:59:38,090 - mineflayer - INFO - at Object.onceWrapper (node:events:628:26)
2023-07-21 18:59:38,090 - mineflayer - INFO - at Client.emit (node:events:525:35)
2023-07-21 18:59:38,090 - mineflayer - INFO - 
2023-07-21 18:59:38,090 - mineflayer - INFO - Node.js v18.16.1

```

**Comment by xieleo5** [comment]
Same as #115, closed.
