### ISSUE TITLE
How to use prismarine-viewer to save the bot-view videos, on my server where no display is supported ?

### ISSUE THREAD

**Issue by OrilinZ** [MineDojo/Voyager#115]

**Comment by OrilinZ** [comment]
2023-07-21 19:32:17,285 - mineflayer - INFO - Stopping subprocess.
2023-07-21 19:32:18,287 - mineflayer - INFO - Starting subprocess with commands: ['node', '/data/zhz_data/Voyager/voyager/env/mineflayer/index.js', '3001']
2023-07-21 19:32:18,743 - mineflayer - INFO - Server started on port 3001
2023-07-21 19:32:18,744 - mineflayer - INFO - Subprocess is ready.
2023-07-21 19:32:18,759 - mineflayer - INFO - {
2023-07-21 19:32:18,759 - mineflayer - INFO - port: 35071,
2023-07-21 19:32:18,759 - mineflayer - INFO - reset: 'hard',
2023-07-21 19:32:18,759 - mineflayer - INFO - inventory: {},
2023-07-21 19:32:18,759 - mineflayer - INFO - equipment: [],
2023-07-21 19:32:18,759 - mineflayer - INFO - spread: false,
2023-07-21 19:32:18,759 - mineflayer - INFO - waitTicks: 20,
2023-07-21 19:32:18,759 - mineflayer - INFO - position: null
2023-07-21 19:32:18,759 - mineflayer - INFO - }
2023-07-21 19:32:21,254 - mineflayer - INFO - THREE.WebGLRenderer: Cannot read properties of null (reading 'getUniformLocation')
2023-07-21 19:32:21,257 - mineflayer - INFO - /data/zhz_data/Voyager/node-canvas-webgl/lib/canvas.js:88
2023-07-21 19:32:21,258 - mineflayer - INFO - const _getUniformLocation = ctx.getUniformLocation;
2023-07-21 19:32:21,258 - mineflayer - INFO - ^
2023-07-21 19:32:21,258 - mineflayer - INFO - 
2023-07-21 19:32:21,258 - mineflayer - INFO - TypeError: Cannot read properties of null (reading 'getUniformLocation')
2023-07-21 19:32:21,258 - mineflayer - INFO - at NodeCanvasElement.getContext (/data/zhz_data/Voyager/node-canvas-webgl/lib/canvas.js:88:39)
2023-07-21 19:32:21,258 - mineflayer - INFO - at getContext (/data/zhz_data/Voyager/voyager/env/mineflayer/node_modules/three/build/three.js:17304:29)
2023-07-21 19:32:21,258 - mineflayer - INFO - at new WebGLRenderer (/data/zhz_data/Voyager/voyager/env/mineflayer/node_modules/three/build/three.js:17335:11)
2023-07-21 19:32:21,258 - mineflayer - INFO - at module.exports (/data/zhz_data/Voyager/voyager/env/mineflayer/node_modules/prismarine-viewer/lib/headless.js:19:20)
2023-07-21 19:32:21,258 - mineflayer - INFO - at EventEmitter.<anonymous> (/data/zhz_data/Voyager/voyager/env/mineflayer/index.js:56:9)
2023-07-21 19:32:21,258 - mineflayer - INFO - at Object.onceWrapper (node:events:627:28)
2023-07-21 19:32:21,258 - mineflayer - INFO - at EventEmitter.emit (node:events:525:35)
2023-07-21 19:32:21,258 - mineflayer - INFO - at Client.<anonymous> (/data/zhz_data/Voyager/voyager/env/mineflayer/node_modules/mineflayer/lib/plugins/health.js:13:11)
2023-07-21 19:32:21,258 - mineflayer - INFO - at Object.onceWrapper (node:events:628:26)
2023-07-21 19:32:21,258 - mineflayer - INFO - at Client.emit (node:events:525:35)
2023-07-21 19:32:21,258 - mineflayer - INFO - 
2023-07-21 19:32:21,258 - mineflayer - INFO - Node.js v18.16.1

**Comment by OrilinZ** [comment]
```
2023-07-21 19:32:17,285 - mineflayer - INFO - Stopping subprocess.
2023-07-21 19:32:18,287 - mineflayer - INFO - Starting subprocess with commands: ['node', '/data/zhz_data/Voyager/voyager/env/mineflayer/index.js', '3001']
2023-07-21 19:32:18,743 - mineflayer - INFO - Server started on port 3001
2023-07-21 19:32:18,744 - mineflayer - INFO - Subprocess is ready.
2023-07-21 19:32:18,759 - mineflayer - INFO - {
2023-07-21 19:32:18,759 - mineflayer - INFO - port: 35071,
2023-07-21 19:32:18,759 - mineflayer - INFO - reset: 'hard',
2023-07-21 19:32:18,759 - mineflayer - INFO - inventory: {},
2023-07-21 19:32:18,759 - mineflayer - INFO - equipment: [],
2023-07-21 19:32:18,759 - mineflayer - INFO - spread: false,
2023-07-21 19:32:18,759 - mineflayer - INFO - waitTicks: 20,
2023-07-21 19:32:18,759 - mineflayer - INFO - position: null
2023-07-21 19:32:18,759 - mineflayer - INFO - }
2023-07-21 19:32:21,254 - mineflayer - INFO - THREE.WebGLRenderer: Cannot read properties of null (reading 'getUniformLocation')
2023-07-21 19:32:21,257 - mineflayer - INFO - /data/zhz_data/Voyager/node-canvas-webgl/lib/canvas.js:88
2023-07-21 19:32:21,258 - mineflayer - INFO - const _getUniformLocation = ctx.getUniformLocation;
2023-07-21 19:32:21,258 - mineflayer - INFO - ^
2023-07-21 19:32:21,258 - mineflayer - INFO - 
2023-07-21 19:32:21,258 - mineflayer - INFO - TypeError: Cannot read properties of null (reading 'getUniformLocation')
2023-07-21 19:32:21,258 - mineflayer - INFO - at NodeCanvasElement.getContext (/data/zhz_data/Voyager/node-canvas-webgl/lib/canvas.js:88:39)
2023-07-21 19:32:21,258 - mineflayer - INFO - at getContext (/data/zhz_data/Voyager/voyager/env/mineflayer/node_modules/three/build/three.js:17304:29)
2023-07-21 19:32:21,258 - mineflayer - INFO - at new WebGLRenderer (/data/zhz_data/Voyager/voyager/env/mineflayer/node_modules/three/build/three.js:17335:11)
2023-07-21 19:32:21,258 - mineflayer - INFO - at module.exports (/data/zhz_data/Voyager/voyager/env/mineflayer/node_modules/prismarine-viewer/lib/headless.js:19:20)
2023-07-21 19:32:21,258 - mineflayer - INFO - at EventEmitter.<anonymous> (/data/zhz_data/Voyager/voyager/env/mineflayer/index.js:56:9)
2023-07-21 19:32:21,258 - mineflayer - INFO - at Object.onceWrapper (node:events:627:28)
2023-07-21 19:32:21,258 - mineflayer - INFO - at EventEmitter.emit (node:events:525:35)
2023-07-21 19:32:21,258 - mineflayer - INFO - at Client.<anonymous> (/data/zhz_data/Voyager/voyager/env/mineflayer/node_modules/mineflayer/lib/plugins/health.js:13:11)
2023-07-21 19:32:21,258 - mineflayer - INFO - at Object.onceWrapper (node:events:628:26)
2023-07-21 19:32:21,258 - mineflayer - INFO - at Client.emit (node:events:525:35)
2023-07-21 19:32:21,258 - mineflayer - INFO - 
2023-07-21 19:32:21,258 - mineflayer - INFO - Node.js v18.16.1
```

**Comment by xieleo5** [comment]
Hi, I'm sorry about the late reply. Prismarine-viewer is not well compatible with Voyager. If you run with a headless server, you can try to use [ReplayMod](https://www.replaymod.com/) to record the server events.
