### ISSUE TITLE
Can't Run Voyager Properly

### ISSUE THREAD

**Issue by ByronChen12138** [MineDojo/Voyager#118]
### Bug Description:
When trying to run the Voyager following the instruction in `README`, A TypeError popped out when using `issubclass(origin, Tuple)`. It may be because of the location of the start file I put. I put the `start.py` file under the folder `Voyager`, the same folder as the `README` file.

Here is the [feedback and the code](https://gist.github.com/ByronChen12138/4842534e0489040951a598ce229d14c5) I used to run Voyager.

### Versions:
**Python:** 3.11
**Node.js:** 18.14.1
**Minecraft:** 1.19
**Fabric:** [1.19] Fabric API 0.58.0+1.19

**Comment by Mr-KayJayDee** [comment]
Same issue here

```py
Traceback (most recent call last):
  File "C:\Users\Killian' DAL-CIN\Desktop\Voyager\index.py", line 1, in <module>
    from voyager import Voyager
  File "C:\Users\Killian' DAL-CIN\Desktop\Voyager\voyager\__init__.py", line 1, in <module>
    from .voyager import Voyager
  File "C:\Users\Killian' DAL-CIN\Desktop\Voyager\voyager\voyager.py", line 10, in <module>
    from .agents import ActionAgent
  File "C:\Users\Killian' DAL-CIN\Desktop\Voyager\voyager\agents\__init__.py", line 1, in <module>
    from .action import ActionAgent
  File "C:\Users\Killian' DAL-CIN\Desktop\Voyager\voyager\agents\action.py", line 6, in <module>
    from langchain.chat_models import ChatOpenAI
  File "C:\Users\Killian' DAL-CIN\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\__init__.py", line 6, in <module>
    from langchain.agents import MRKLChain, ReActChain, SelfAskWithSearchChain
  File "C:\Users\Killian' DAL-CIN\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\agents\__init__.py", line 31, in <module>
    from langchain.agents.agent import (
  File "C:\Users\Killian' DAL-CIN\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\agents\agent.py", line 23, in <module>
    from langchain.agents.agent_iterator import AgentExecutorIterator
  File "C:\Users\Killian' DAL-CIN\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\agents\agent_iterator.py", line 30, in <module>
    from langchain.tools import BaseTool
  File "C:\Users\Killian' DAL-CIN\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\tools\__init__.py", line 25, in <module>
    from langchain.tools.arxiv.tool import ArxivQueryRun
  File "C:\Users\Killian' DAL-CIN\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\tools\arxiv\tool.py", line 8, in <module>
    from langchain.utilities.arxiv import ArxivAPIWrapper
  File "C:\Users\Killian' DAL-CIN\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\utilities\__init__.py", line 7, in <module>
    from langchain.utilities.apify import ApifyWrapper
  File "C:\Users\Killian' DAL-CIN\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\utilities\apify.py", line 3, in <module>
    from langchain.document_loaders import ApifyDatasetLoader
  File "C:\Users\Killian' DAL-CIN\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\document_loaders\__init__.py", line 76, in <module>
    from langchain.document_loaders.embaas import EmbaasBlobLoader, EmbaasLoader
  File "C:\Users\Killian' DAL-CIN\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\document_loaders\embaas.py", line 54, in <module>
    class BaseEmbaasLoader(BaseModel):
  File "pydantic\main.py", line 204, in pydantic.main.ModelMetaclass.__new__
  File "pydantic\fields.py", line 488, in pydantic.fields.ModelField.infer
  File "pydantic\fields.py", line 419, in pydantic.fields.ModelField.__init__
  File "pydantic\fields.py", line 539, in pydantic.fields.ModelField.prepare
  File "pydantic\fields.py", line 801, in pydantic.fields.ModelField.populate_validators
  File "pydantic\validators.py", line 696, in find_validators
  File "pydantic\validators.py", line 585, in pydantic.validators.make_typeddict_validator
  File "pydantic\annotated_types.py", line 35, in pydantic.annotated_types.create_model_from_typeddict
  File "pydantic\main.py", line 972, in pydantic.main.create_model
  File "pydantic\main.py", line 204, in pydantic.main.ModelMetaclass.__new__
  File "pydantic\fields.py", line 488, in pydantic.fields.ModelField.infer
  File "pydantic\fields.py", line 419, in pydantic.fields.ModelField.__init__
  File "pydantic\fields.py", line 534, in pydantic.fields.ModelField.prepare
  File "pydantic\fields.py", line 638, in pydantic.fields.ModelField._type_analysis
  File "C:\Users\Killian' DAL-CIN\AppData\Local\Programs\Python\Python310\lib\typing.py", line 1134, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class
```

**Comment by Poseidon0901** [comment]
you really use the openai api key like `sk-...XXX` or just protect the key because the key must belike `sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx`
