### ISSUE TITLE
bot doesn't come in

### ISSUE THREAD

**Issue by VinDmiAnd** [MineDojo/Voyager#126]
C:\Users\dimav\Voyager>python bot.py
Mineflayer process has exited, restarting
Subprocess mineflayer started with PID 21928.
Server started on port 3000

Traceback (most recent call last):
  File "C:\Users\dimav\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 790, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimav\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimav\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connection.py", line 461, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimav\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1374, in getresponse
    response.begin()
  File "C:\Users\dimav\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimav\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dimav\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\dimav\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 844, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimav\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimav\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\dimav\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 790, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimav\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimav\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connection.py", line 461, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimav\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1374, in getresponse
    response.begin()
  File "C:\Users\dimav\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimav\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dimav\Voyager\bot.py", line 11, in <module>
    voyager.learn()
  File "C:\Users\dimav\Voyager\voyager\voyager.py", line 306, in learn
    self.env.reset(
  File "C:\Users\dimav\Voyager\voyager\env\bridge.py", line 156, in reset
    returned_data = self.check_process()
                    ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimav\Voyager\voyager\env\bridge.py", line 93, in check_process
    res = requests.post(
          ^^^^^^^^^^^^^^
  File "C:\Users\dimav\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimav\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimav\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimav\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimav\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
![Снимок экрана 2023-09-15 175753](https://github.com/MineDojo/Voyager/assets/144416680/0c7f6911-1532-4911-b408-ad4818596402)

**Comment by VinDmiAnd** [comment]
It’s not clear why there is such an error, why there are different errors, if there is a different version and there are no mods, other errors, but with the corresponding mods, here is the error that I threw off

**Comment by VinDmiAnd** [comment]
Microsoft Windows [Version 10.0.22621.2283]
(c) Корпорация Майкрософт (Microsoft Corporation). Все права защищены.

C:\Users\dimav>pip install --upgrade requests
Requirement already satisfied: requests in c:\users\dimav\appdata\local\programs\python\python311\lib\site-packages (2.31.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\dimav\appdata\local\programs\python\python311\lib\site-packages (from requests) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\dimav\appdata\local\programs\python\python311\lib\site-packages (from requests) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\dimav\appdata\local\programs\python\python311\lib\site-packages (from requests) (2.0.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\dimav\appdata\local\programs\python\python311\lib\site-packages (from requests) (2023.7.22)

C:\Users\dimav>cd voyager

C:\Users\dimav\Voyager>python311 bot.py
"python311" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.

C:\Users\dimav\Voyager>python bot.py
Mineflayer process has exited, restarting
Subprocess mineflayer started with PID 8372.
Server started on port 3000

Traceback (most recent call last):
  File "C:\Users\dimav\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 790, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimav\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimav\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connection.py", line 461, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimav\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1374, in getresponse
    response.begin()
  File "C:\Users\dimav\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimav\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 300, in _read_status
    raise BadStatusLine(line)
http.client.BadStatusLine: Ö4B¦ÇºÞVßul·=c¾ïQÍ{q!^[4{Z¤V`bë¡#rê¬üÚo\©J§ù@,»Ú2dl[¯LuÔr7ÜKáh'°¿kÄ¸ânF¨0*ïÚìðÄ$]½¦"¸õxm²                                                                                                                     ²7ê²§Ü{xðN¡lÇ7îj×t½J¿¶ Ý¨nôCä×ûÃÎ>¨º      Ó«~î2¢~#IG+ÌMt½mK°om»{dÞë÷Þ¥qbæ
ñJu¥ÅL¹ë{R^q¶SÖ"©ø¼sâ l½Ï#÷ÿötÉ×«  AÜý(.]Ü²Á¡~oKd~=Ã"


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dimav\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\dimav\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 844, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimav\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimav\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\dimav\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 790, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimav\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimav\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connection.py", line 461, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimav\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1374, in getresponse
    response.begin()
  File "C:\Users\dimav\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimav\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 300, in _read_status
    raise BadStatusLine(line)
urllib3.exceptions.ProtocolError: ('Connection aborted.', BadStatusLine('\x03\x8eÖ\x074\x87B¦ÇºÞ\x92Vßu\x8cl·\x9b=c¾ïQÍ{q!^[4{Z¤V`bë\x9a¡#rê¬\x87\x7füÚo\\©J\x95§ù\x19\x8d@,»Ú2d\x9el[¯\x8cLu\x00Ôr7ÜKáh\'°¿kÄ\x8e¸ân\x19F¨0*\x07ïÚìðÄ$]½¦"\x18¸õ\x9e\x92xm²\x11\x137ê\x9d²\x14§Ü\x1f\x18{xðN¡lÇ7î\x1cj×t½J¿¶\xa0Ý\x06¨nôCä×\x82ûÃÎ>¨º\tÓ«~\x9aî2\x95¢~#I\x98\x02G+ÌMt½mK°om\x1b\x16\x14l\x1b«\x8f\x92»{\x8adÞë÷Þ¥qbæ\x0b~ê¦%^+C_\x11\x97\x1cú#îf\x17û¸VþrNÎî\x1c|=\x01\x91\xa0OÈ\x82\x1d×Ô_tÉ×\x82\x1b\x7fÕ«\tAÜ\x8eý\x8e(.]Ü²Á¡~oKd~=Ã"\t\rñJu\x11¥ÅL¹\x0eë{R^\x89q¶SÖ"\x01©\x1aø¼s\x82â\x15 l½Ï#\x9d\x9e\x86\x9e÷ÿ\x1dö\n'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dimav\Voyager\bot.py", line 11, in <module>
    voyager.learn()
  File "C:\Users\dimav\Voyager\voyager\voyager.py", line 306, in learn
    self.env.reset(
  File "C:\Users\dimav\Voyager\voyager\env\bridge.py", line 156, in reset
    returned_data = self.check_process()
                    ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimav\Voyager\voyager\env\bridge.py", line 93, in check_process
    res = requests.post(
          ^^^^^^^^^^^^^^
  File "C:\Users\dimav\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimav\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimav\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimav\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimav\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine('\x03\x8eÖ\x074\x87B¦ÇºÞ\x92Vßu\x8cl·\x9b=c¾ïQÍ{q!^[4{Z¤V`bë\x9a¡#rê¬\x87\x7füÚo\\©J\x95§ù\x19\x8d@,»Ú2d\x9el[¯\x8cLu\x00Ôr7ÜKáh\'°¿kÄ\x8e¸ân\x19F¨0*\x07ïÚìðÄ$]½¦"\x18¸õ\x9e\x92xm²\x11\x137ê\x9d²\x14§Ü\x1f\x18{xðN¡lÇ7î\x1cj×t½J¿¶\xa0Ý\x06¨nôCä×\x82ûÃÎ>¨º\tÓ«~\x9aî2\x95¢~#I\x98\x02G+ÌMt½mK°om\x1b\x16\x14l\x1b«\x8f\x92»{\x8adÞë÷Þ¥qbæ\x0b~ê¦%^+C_\x11\x97\x1cú#îf\x17û¸VþrNÎî\x1c|=\x01\x91\xa0OÈ\x82\x1d×Ô_tÉ×\x82\x1b\x7fÕ«\tAÜ\x8eý\x8e(.]Ü²Á¡~oKd~=Ã"\t\rñJu\x11¥ÅL¹\x0eë{R^\x89q¶SÖ"\x01©\x1aø¼s\x82â\x15 l½Ï#\x9d\x9e\x86\x9e÷ÿ\x1dö\n')) 
this is the next problem

**Comment by Coppelian** [comment]
Hi [VinDmiAnd](https://github.com/VinDmiAnd),

I faced a problem when I try to set up this project.
```
npx tsc
src/BlockVeins.ts:25:32 - error TS2345: Argument of type 'import("/home/coppelia/Program/Voyager/voyager/env/mineflayer/node_modules/mineflayer/node_modules/prismarine-block/index").Block' is not assignable to parameter of type 'import("/home/coppelia/Program/Voyager/voyager/env/mineflayer/node_modules/prismarine-block/index").Block'.
  The types returned by 'getProperties()' are incompatible between these types.
    Type '{ [key: string]: string | number | boolean; }' is not assignable to type '{ [key: string]: string | number; }'.
      'string' index signatures are incompatible.
        Type 'string | number | boolean' is not assignable to type 'string | number'.
          Type 'boolean' is not assignable to type 'string | number'.

25           if (targets.includes(neighbor)) continue
                                  ~~~~~~~~

src/BlockVeins.ts:26:29 - error TS2345: Argument of type 'import("/home/coppelia/Program/Voyager/voyager/env/mineflayer/node_modules/mineflayer/node_modules/prismarine-block/index").Block' is not assignable to parameter of type 'import("/home/coppelia/Program/Voyager/voyager/env/mineflayer/node_modules/prismarine-block/index").Block'.

26           if (open.includes(neighbor)) continue
                               ~~~~~~~~

src/BlockVeins.ts:28:21 - error TS2345: Argument of type 'import("/home/coppelia/Program/Voyager/voyager/env/mineflayer/node_modules/mineflayer/node_modules/prismarine-block/index").Block' is not assignable to parameter of type 'import("/home/coppelia/Program/Voyager/voyager/env/mineflayer/node_modules/prismarine-block/index").Block'.

28           open.push(neighbor)
                       ~~~~~~~~

src/CollectBlock.ts:209:23 - error TS2345: Argument of type 'import("/home/coppelia/Program/Voyager/voyager/env/mineflayer/node_modules/prismarine-block/index").Block' is not assignable to parameter of type 'import("/home/coppelia/Program/Voyager/voyager/env/mineflayer/node_modules/mineflayer/node_modules/prismarine-block/index").Block'.
  Type 'Block' is missing the following properties from type 'Block': setSignText, getSignText

209         await bot.dig(block);
                          ~~~~~


Found 4 errors in 2 files.

Errors  Files
     3  src/BlockVeins.ts:25
     1  src/CollectBlock.ts:209

```
This error occurs when I tried to use npx tsc command.
Could you shed a light on how to set up this program successfully?
Thank you.
