### ISSUE TITLE
`openai` has no `ChatCompletion` attribute

### ISSUE THREAD

**Issue by SomeoneSon** [MineDojo/Voyager#132]
Have error with 1 start, upgrade lib not help

Traceback (most recent call last):
  File "C:\Python Projects\Voyager\test.py", line 12, in <module>
    voyager = Voyager(
  File "C:\Python Projects\Voyager\voyager\voyager.py", line 118, in __init__
    self.action_agent = ActionAgent(
  File "C:\Python Projects\Voyager\voyager\agents\action.py", line 34, in __init__
    self.llm = ChatOpenAI(
  File "C:\Users\soenon\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\load\serializable.py", line 97, in __init__
    super().__init__(**kwargs)
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for ChatOpenAI
__root__
  `openai` has no `ChatCompletion` attribute, this is likely due to an old version of the openai package. Try upgrading it with `pip install --upgrade openai`. (type=value_error)

**Comment by SomeoneSon** [comment]
**solved**

if u have same issue use 
pip uninstall openai
pip install "openai<1.0.0"
