### ISSUE TITLE
setuptools does not work (wrong gpg version (gpg1.14.0-unknown))

### ISSUE THREAD

**Issue by Sedrowow** [MineDojo/Voyager#137]
### Before submitting an issue, make sure you read the [FAQ.md](FAQ.md)
i did read the faq
### Briefly describe your issue
...so i try to install the latest voyager with pip install -e /home/sedrowow/Voyager (location of the setup.py). everything works but it fails on setup.py saying that the easy_install command is deprecated.
### Please provide your python, nodejs, Minecraft, and Fabric versions here
...python 3.9
nodejs 7.5.2
### [If applicable] Please provide the Minefalyer and Minecraft logs, you can find the log under logs folder
`    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/sedrowow/Voyager/setup.py'"'"'; __file__='"'"'/home/sedrowow/Voyager/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /home/sedrowow/Voyager/
    Complete output (36 lines):
    running develop
    /usr/lib/python3/dist-packages/setuptools/command/easy_install.py:146: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    /usr/lib/python3/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/sedrowow/Voyager/setup.py", line 32, in <module>
        setup(
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 108, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.9/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.9/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 1213, in run_command
        super().run_command(command)
      File "/usr/lib/python3.9/distutils/dist.py", line 984, in run_command
        cmd_obj.ensure_finalized()
      File "/usr/lib/python3.9/distutils/cmd.py", line 107, in ensure_finalized
        self.finalize_options()
      File "/usr/lib/python3/dist-packages/setuptools/command/develop.py", line 52, in finalize_options
        easy_install.finalize_options(self)
      File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 335, in finalize_options
        self.local_index = Environment(self.shadow_path + sys.path)
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1044, in __init__
        self.scan(search_path)
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1077, in scan
        self.add(dist)
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1096, in add
        dists.sort(key=operator.attrgetter('hashcmp'), reverse=True)
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2631, in hashcmp
        self.parsed_version,
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2685, in parsed_version
        raise packaging.version.InvalidVersion(f"{str(ex)} {info}") from None
    pkg_resources.extern.packaging.version.InvalidVersion: Invalid version: '1.14.0-unknown' (package: gpg)
`
### [If applicable] Please provide the GPT conversations that are printed each round.
...

**Comment by Sedrowow** [comment]
i think i found the possible real error here. its an issue by debian with the gpg package.

what i will do: i will manually install gpg following the guide on https://www.procustodibus.com/blog/2023/02/gpg-2-4-on-ubuntu-22-04/

and if setup.py works after that. i will close the issue else, ill report back

**Comment by Sedrowow** [comment]
ok i think i overcomplicated the solution

i just reinstalled gpg with "sudo apt install gpg"... but the guidemight have helped to get it working.

now it installed succesfully
