### ISSUE TITLE
Cannot start after following the steps described in the installation

### ISSUE THREAD

**Issue by hiro2264** [MineDojo/Voyager#168]
### Before submitting an issue, make sure you read the [FAQ.md](FAQ.md)
Sure!
### Briefly describe your issue
When I try to start learning and agent operation with Voyager, I get the following error and cannot start.
I have tried to address the same issue in multiple environments and have raised this issue because I am getting the same error messeages.
#### On Windows10 env
Python     : 3.10.6
Node        : 20.12.2
Minecraft : 1.19
Fabric       : 0.14.18
minecraft is launch by curseforge but mods are manual install.
#### On same PC, VMware workstation 17.5.x Ubuntu 22.04.4 LTS
Python3   : 3.10.12
Node        : 20.16.0
Minecraft : 1.19
Fabric       : 0.14.18
mods are same on windows environment.
#### Error when trying to run Voyager in a Windows environment.
    2024-08-17 02:40:17,829 - mineflayer - INFO - Stopping subprocess.
    2024-08-17 02:40:18,830 - mineflayer - INFO - Starting subprocess with commands: ['node', 
    'D:\\Voyager5\\Voyager\\voyager\\env\\mineflayer/index.js', '3000']
    2024-08-17 02:40:19,322 - mineflayer - INFO - node:events:496
    2024-08-17 02:40:19,323 - mineflayer - INFO - throw er; // Unhandled 'error' event
    2024-08-17 02:40:19,323 - mineflayer - INFO - ^
    2024-08-17 02:40:19,323 - mineflayer - INFO - 
    2024-08-17 02:40:19,323 - mineflayer - INFO - Error: listen EADDRINUSE: address already in use :::3000
    2024-08-17 02:40:19,323 - mineflayer - INFO - [90m    at Server.setupListenHandle [as _listen2] (node:net:1897:16)[39m
    2024-08-17 02:40:19,323 - mineflayer - INFO - [90m    at listenInCluster (node:net:1945:12)[39m
    2024-08-17 02:40:19,324 - mineflayer - INFO - [90m    at Server.listen (node:net:2037:7)[39m
    2024-08-17 02:40:19,324 - mineflayer - INFO - at Function.listen 
    [90m(D:\Voyager5\Voyager\[39mvoyager\env\mineflayer\node_modules\[4mexpress[24m\lib\application.js:635:24[90m)[39m
    2024-08-17 02:40:19,324 - mineflayer - INFO - at Object.<anonymous> 
    [90m(D:\Voyager5\Voyager\[39mvoyager\env\mineflayer\index.js:423:5[90m)[39m
    2024-08-17 02:40:19,324 - mineflayer - INFO - [90m    at Module._compile (node:internal/modules/cjs/loader:1369:14)[39m
    2024-08-17 02:40:19,324 - mineflayer - INFO - [90m    at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)[39m
    2024-08-17 02:40:19,324 - mineflayer - INFO - [90m    at Module.load (node:internal/modules/cjs/loader:1206:32)[39m
    2024-08-17 02:40:19,324 - mineflayer - INFO - [90m    at Module._load (node:internal/modules/cjs/loader:1022:12)[39m
    2024-08-17 02:40:19,324 - mineflayer - INFO - [90m    at Function.executeUserEntryPoint [as runMain]     (node:internal/modules/run_main:135:12)[39m
    2024-08-17 02:40:19,324 - mineflayer - INFO - Emitted 'error' event on Server instance at:
    2024-08-17 02:40:19,324 - mineflayer - INFO - [90m    at emitErrorNT (node:net:1924:8)[39m
    2024-08-17 02:40:19,324 - mineflayer - INFO - [90m    at process.processTicksAndRejections     (node:internal/process/task_queues:82:21)[39m {
    2024-08-17 02:40:19,324 - mineflayer - INFO - code: [32m'EADDRINUSE'[39m,
    2024-08-17 02:40:19,324 - mineflayer - INFO - errno: [33m-4091[39m,
    2024-08-17 02:40:19,324 - mineflayer - INFO - syscall: [32m'listen'[39m,
    2024-08-17 02:40:19,324 - mineflayer - INFO - address: [32m'::'[39m,
    2024-08-17 02:40:19,324 - mineflayer - INFO - port: [33m3000[39m
    2024-08-17 02:40:19,324 - mineflayer - INFO - }
    2024-08-17 02:40:19,324 - mineflayer - INFO - 
    2024-08-17 02:40:19,324 - mineflayer - INFO - Node.js v20.12.2
    2024-08-17 02:40:19,333 - mineflayer - INFO - Starting subprocess with commands: ['node',     'D:\\Voyager5\\Voyager\\voyager\\env\\mineflayer/index.js', '3000']
    2024-08-17 02:40:19,801 - mineflayer - INFO - node:events:496
The above error logs will continue to flow until Voyager is stopped.
� is esc mark.
#### Error when trying to run Voyager's mineflayer in a Windows environment.(Performed according to https://github.com/MineDojo/Voyager/blob/main/FAQ.md#i-got-subprocess-mineflayer-failed-to-start-error)

        PS D:\Voyager5\Voyager\voyager\env\mineflayer> node index.js
    node:events:496
          throw er; // Unhandled 'error' event
          ^
    
    Error: listen EADDRINUSE: address already in use :::3000
        at Server.setupListenHandle [as _listen2] (node:net:1897:16)
        at listenInCluster (node:net:1945:12)
        at Server.listen (node:net:2037:7)
        at Function.listen (D:\Voyager5\Voyager\voyager\env\mineflayer\node_modules\express\lib\application.js:635:24)
        at Object.<anonymous> (D:\Voyager5\Voyager\voyager\env\mineflayer\index.js:423:5)
        at Module._compile (node:internal/modules/cjs/loader:1369:14)
        at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
        at Module.load (node:internal/modules/cjs/loader:1206:32)
        at Module._load (node:internal/modules/cjs/loader:1022:12)
        at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    Emitted 'error' event on Server instance at:
        at emitErrorNT (node:net:1924:8)
        at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
      code: 'EADDRINUSE',
      errno: -4091,
      syscall: 'listen',
      address: '::',
      port: 3000
    }
    
    Node.js v20.12.2
Only Mineflayer, when launched in a Windows environment, succeeded in spawning bots and other basic behaviors.

After many errors, I tried to start using Curseforge instead of TLauncher with the following video as a reference, and the following error occurred in a VMware-based environment.
#### Error when trying to run Voyager in a Ubuntu environment.
    2024-08-16 19:52:17,796 - mineflayer - INFO - Stopping subprocess.
    2024-08-16 19:52:18,799 - mineflayer - INFO - Starting subprocess with commands: ['node', 
    '/home/voyager/Voyager/voyager/env/mineflayer/index.js', '3000']
    2024-08-16 19:52:19,318 - mineflayer - INFO - Server started on port 3000
    2024-08-16 19:52:19,318 - mineflayer - INFO - Subprocess is ready.
    2024-08-16 19:52:19,332 - mineflayer - INFO - {
    2024-08-16 19:52:19,332 - mineflayer - INFO - port: '${3000}',
    2024-08-16 19:52:19,332 - mineflayer - INFO - reset: 'hard',
    2024-08-16 19:52:19,332 - mineflayer - INFO - inventory: {},
    2024-08-16 19:52:19,332 - mineflayer - INFO - equipment: [],
    2024-08-16 19:52:19,332 - mineflayer - INFO - spread: false,
    2024-08-16 19:52:19,332 - mineflayer - INFO - waitTicks: 20,
    2024-08-16 19:52:19,332 - mineflayer - INFO - position: null
    2024-08-16 19:52:19,332 - mineflayer - INFO - }
    2024-08-16 19:52:19,805 - mineflayer - INFO - Error: connect ENOENT ${3000}
    2024-08-16 19:52:19,805 - mineflayer - INFO - at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1607:16) {
    2024-08-16 19:52:19,805 - mineflayer - INFO - errno: -2,
    2024-08-16 19:52:19,805 - mineflayer - INFO - code: 'ENOENT',
    2024-08-16 19:52:19,805 - mineflayer - INFO - syscall: 'connect',
    2024-08-16 19:52:19,805 - mineflayer - INFO - address: '${3000}'
    2024-08-16 19:52:19,805 - mineflayer - INFO - }
    2024-08-16 19:52:19,805 - mineflayer - INFO - Error: connect ENOENT ${3000}
    2024-08-16 19:52:19,805 - mineflayer - INFO - at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1607:16) {
    2024-08-16 19:52:19,805 - mineflayer - INFO - errno: -2,
    2024-08-16 19:52:19,806 - mineflayer - INFO - code: 'ENOENT',
    2024-08-16 19:52:19,806 - mineflayer - INFO - syscall: 'connect',
    2024-08-16 19:52:19,806 - mineflayer - INFO - address: '${3000}'
    2024-08-16 19:52:19,806 - mineflayer - INFO - }
    2024-08-16 19:52:19,808 - mineflayer - INFO - Stopping subprocess.
#### Error when trying to run Voyager's mineflayer in a Ubuntu environment.
    voyager@voyager-virtual-machine:~/Voyager$ cd voyager/env/mineflayer
    node index.js
    node:events:497
          throw er; // Unhandled 'error' event
          ^
    
    Error: listen EADDRINUSE: address already in use :::3000
        at Server.setupListenHandle [as _listen2] (node:net:1904:16)
        at listenInCluster (node:net:1961:12)
        at Server.listen (node:net:2063:7)
        at Function.listen (/home/voyager/Voyager/voyager/env/mineflayer/node_modules/express/lib/application.js:635:24)
        at Object.<anonymous> (/home/voyager/Voyager/voyager/env/mineflayer/index.js:423:5)
        at Module._compile (node:internal/modules/cjs/loader:1358:14)
        at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
        at Module.load (node:internal/modules/cjs/loader:1208:32)
        at Module._load (node:internal/modules/cjs/loader:1024:12)
        at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
    Emitted 'error' event on Server instance at:
        at emitErrorNT (node:net:1940:8)
        at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
      code: 'EADDRINUSE',
      errno: -98,
      syscall: 'listen',
      address: '::',
      port: 3000
    }
    
    Node.js v20.16.0
### Just a little something
I could not quite get it to boot up in the windows environment properly, so I created a VMware environment as an alternative. However, the VMware-based environment is extremely heavy (30 fps at 5950x and nothing else!), so I would like to solve this problem in the windows environment if possible.
This is my first time writing an issue and it is mostly machine translation, so please let me know if there is anything I have missed.

**Comment by hiro2264** [comment]
I felt the name of the issue was incorrect, so I fixed it.
