### ISSUE TITLE
An existing connection was forcibly closed by the remote host (10054)

### ISSUE THREAD

**Issue by longlongerbao** [MineDojo/Voyager#170]
### Before submitting an issue, make sure you read the [FAQ.md](FAQ.md)
Yes
### Briefly describe your issue
...
Start the script,then join a server.Once joined then instantly dropped and show an error: File "E:\Python3.11\Lib\site-packages\requests\adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
### Please provide your python, nodejs, Minecraft, and Fabric versions here
...
Python 3.11
nodejs: 'v20.17.0'
minecraft:1.19.4
fabic:0.16.5
### [If applicable] Please provide the Minefalyer and Minecraft logs, you can find the log under `logs` folder
...
2024-09-11 23:04:02,098 - mineflayer - INFO - Stopping subprocess.
2024-09-11 23:04:03,122 - mineflayer - INFO - Starting subprocess with commands: ['node', 'F:\\youxi\\minecraft\\AI\\Voyager\\Bin\\voyager\\env\\mineflayer/index.js', '3000']
2024-09-11 23:04:04,028 - mineflayer - INFO - Server started on port 3000
2024-09-11 23:04:04,029 - mineflayer - INFO - Subprocess is ready.
2024-09-11 23:04:04,099 - mineflayer - INFO - {
2024-09-11 23:04:04,099 - mineflayer - INFO - port: '25565',
2024-09-11 23:04:04,099 - mineflayer - INFO - reset: 'hard',
2024-09-11 23:04:04,099 - mineflayer - INFO - inventory: {},
2024-09-11 23:04:04,101 - mineflayer - INFO - equipment: [],
2024-09-11 23:04:04,101 - mineflayer - INFO - spread: false,
2024-09-11 23:04:04,101 - mineflayer - INFO - waitTicks: 20,
2024-09-11 23:04:04,101 - mineflayer - INFO - position: null
2024-09-11 23:04:04,101 - mineflayer - INFO - }
2024-09-11 23:04:05,385 - mineflayer - INFO - Mineflayer detected that you are using a deprecated event (physicTick)! Please use this event (physicsTick) instead.
2024-09-11 23:04:05,391 - mineflayer - INFO - node:internal/process/promises:391
2024-09-11 23:04:05,391 - mineflayer - INFO - triggerUncaughtException(err, true /* fromPromise */);
2024-09-11 23:04:05,391 - mineflayer - INFO - ^
2024-09-11 23:04:05,391 - mineflayer - INFO - 
2024-09-11 23:04:05,391 - mineflayer - INFO - AssertionError [ERR_ASSERTION]: plugin needs to be a function
2024-09-11 23:04:05,391 - mineflayer - INFO - at EventEmitter.loadPlugin (F:\youxi\minecraft\AI\Voyager\Bin\voyager\env\mineflayer\node_modules\mineflayer\lib\plugin_loader.js:16:12)
2024-09-11 23:04:05,391 - mineflayer - INFO - at EventEmitter.<anonymous> (F:\youxi\minecraft\AI\Voyager\Bin\voyager\env\mineflayer\index.js:107:13)
2024-09-11 23:04:05,391 - mineflayer - INFO - at Object.onceWrapper (node:events:633:28)
2024-09-11 23:04:05,391 - mineflayer - INFO - at EventEmitter.emit (node:events:531:35)
2024-09-11 23:04:05,391 - mineflayer - INFO - at Client.<anonymous> (F:\youxi\minecraft\AI\Voyager\Bin\voyager\env\mineflayer\node_modules\mineflayer\lib\plugins\health.js:13:11)
2024-09-11 23:04:05,391 - mineflayer - INFO - at Object.onceWrapper (node:events:634:26)
2024-09-11 23:04:05,391 - mineflayer - INFO - at Client.emit (node:events:531:35)
2024-09-11 23:04:05,391 - mineflayer - INFO - at emitPacket (F:\youxi\minecraft\AI\Voyager\Bin\voyager\env\mineflayer\node_modules\minecraft-protocol\src\client.js:83:12)
2024-09-11 23:04:05,391 - mineflayer - INFO - at FullPacketParser.<anonymous> (F:\youxi\minecraft\AI\Voyager\Bin\voyager\env\mineflayer\node_modules\minecraft-protocol\src\client.js:112:9)
2024-09-11 23:04:05,391 - mineflayer - INFO - at FullPacketParser.emit (node:events:519:28) {
2024-09-11 23:04:05,393 - mineflayer - INFO - generatedMessage: false,
2024-09-11 23:04:05,393 - mineflayer - INFO - code: 'ERR_ASSERTION',
2024-09-11 23:04:05,393 - mineflayer - INFO - actual: false,
2024-09-11 23:04:05,393 - mineflayer - INFO - expected: true,
2024-09-11 23:04:05,393 - mineflayer - INFO - operator: '=='
2024-09-11 23:04:05,393 - mineflayer - INFO - }
2024-09-11 23:04:05,393 - mineflayer - INFO - 
2024-09-11 23:04:05,393 - mineflayer - INFO - Node.js v20.17.0

### [If applicable] Please provide the GPT conversations that are printed each round.
...

**Comment by longlongerbao** [comment]
solved it using the same process here https://github.com/MineDojo/Voyager/issues/155
