### ISSUE TITLE
Creating Minecraft server  ERROR

### ISSUE THREAD

**Issue by droc12** [MineDojo/Voyager#32]
Traceback (most recent call last):
  File "/Users/roc/tool/Voyager/ttest.py", line 12, in <module>
    voyager = Voyager(
  File "/Users/roc/tool/Voyager/voyager/voyager.py", line 102, in __init__
    self.env = VoyagerEnv(
  File "/Users/roc/tool/Voyager/voyager/env/bridge.py", line 42, in __init__
    self.mc_instance = self.get_mc_instance()
  File "/Users/roc/tool/Voyager/voyager/env/bridge.py", line 67, in get_mc_instance
    return MinecraftInstance(
  File "/Users/roc/tool/Voyager/voyager/env/minecraft_launcher.py", line 36, in __init__
    self.mc_command = self.get_mc_command()
  File "/Users/roc/tool/Voyager/voyager/env/minecraft_launcher.py", line 89, in get_mc_command
    login_data = minecraft_launcher_lib.microsoft_account.complete_login(
  File "/Users/roc/miniconda3/lib/python3.10/site-packages/minecraft_launcher_lib/microsoft_account.py", line 261, in complete_login
    token = token_request["access_token"]
KeyError: 'access_token'

**Comment by nathan-gage** [comment]
bump;

apple m1 w/ Azure login

**Comment by MatthewPDingle** [comment]
Same error, Windows 11 & Azure login

**Comment by xieleo5** [comment]
Hi, all. Someone reported in #34  that changing `Desktop and Mobile` to `Web` could potentially solve this issue. However on my own computer, only `Desktop and Mobile` works. I am unsure if this discrepancy is due to a difference in OS. Could you please try both methods and see whether they work?

**Comment by droc12** [comment]
Thank you for your reply. I tried both methods, but neither worked.

**Comment by Roesilej** [comment]
Having this problem as well. Windows 10 & Azure login

**Comment by GoingMyWay** [comment]
Have you managed to solve it?

**Comment by droc12** [comment]
> Have you managed to solve it?

I haven't solved it yet.
