### ISSUE TITLE
ConnectionError

### ISSUE THREAD

**Issue by nanjiangwill** [MineDojo/Voyager#45]
`raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Stopping mineflayer`

What might be the reason for this? I am using Azure Login

**Comment by go-maple** [comment]
You used the VPN or other proxy?

**Comment by nanjiangwill** [comment]
I did not

**Comment by xieleo5** [comment]
Hi, can you share your Mineflayer log under `logs/mineflayer`?

**Comment by nanjiangwill** [comment]
`2023-05-30 16:11:47,547 - mineflayer - INFO - Stopping subprocess.
2023-05-30 16:12:35,739 - mineflayer - INFO - Starting subprocess with commands: ['node', '/Users/willjiang/Desktop/web3dev/Voyager/voyager/env/mineflayer/index.js', '3000']
2023-05-30 16:12:36,198 - mineflayer - INFO - Server started on port 3000
2023-05-30 16:12:36,198 - mineflayer - INFO - Subprocess is ready.
2023-05-30 16:12:36,211 - mineflayer - INFO - {
2023-05-30 16:12:36,211 - mineflayer - INFO - port: 58262,
2023-05-30 16:12:36,211 - mineflayer - INFO - reset: 'hard',
2023-05-30 16:12:36,211 - mineflayer - INFO - inventory: {},
2023-05-30 16:12:36,211 - mineflayer - INFO - equipment: [],
2023-05-30 16:12:36,211 - mineflayer - INFO - spread: false,
2023-05-30 16:12:36,211 - mineflayer - INFO - waitTicks: 20,
2023-05-30 16:12:36,211 - mineflayer - INFO - position: null
2023-05-30 16:12:36,211 - mineflayer - INFO - }
2023-05-30 16:12:37,036 - mineflayer - INFO - PartialReadError: Read error for undefined : undefined
2023-05-30 16:12:37,036 - mineflayer - INFO - at new ExtendableError (/Users/willjiang/Desktop/web3dev/Voyager/voyager/env/mineflayer/node_modules/protodef/src/utils.js:63:13)
2023-05-30 16:12:37,036 - mineflayer - INFO - at new PartialReadError (/Users/willjiang/Desktop/web3dev/Voyager/voyager/env/mineflayer/node_modules/protodef/src/utils.js:70:5)
2023-05-30 16:12:37,036 - mineflayer - INFO - at Object.readVarInt [as varint] (/Users/willjiang/Desktop/web3dev/Voyager/voyager/env/mineflayer/node_modules/protodef/src/datatypes/utils.js:69:45)
2023-05-30 16:12:37,036 - mineflayer - INFO - at eval (eval at compile (/Users/willjiang/Desktop/web3dev/Voyager/voyager/env/mineflayer/node_modules/protodef/src/compiler.js:258:12), <anonymous>:241:59)
2023-05-30 16:12:37,036 - mineflayer - INFO - at Object.entityMetadata (eval at compile (/Users/willjiang/Desktop/web3dev/Voyager/voyager/env/mineflayer/node_modules/protodef/src/compiler.js:258:12), <anonymous>:244:9)
2023-05-30 16:12:37,036 - mineflayer - INFO - at Object.packet_entity_metadata (eval at compile (/Users/willjiang/Desktop/web3dev/Voyager/voyager/env/mineflayer/node_modules/protodef/src/compiler.js:258:12), <anonymous>:1778:73)
2023-05-30 16:12:37,036 - mineflayer - INFO - at eval (eval at compile (/Users/willjiang/Desktop/web3dev/Voyager/voyager/env/mineflayer/node_modules/protodef/src/compiler.js:258:12), <anonymous>:2398:70)
2023-05-30 16:12:37,036 - mineflayer - INFO - at packet (eval at compile (/Users/willjiang/Desktop/web3dev/Voyager/voyager/env/mineflayer/node_modules/protodef/src/compiler.js:258:12), <anonymous>:2428:9)
2023-05-30 16:12:37,036 - mineflayer - INFO - at CompiledProtodef.read (/Users/willjiang/Desktop/web3dev/Voyager/voyager/env/mineflayer/node_modules/protodef/src/compiler.js:70:12)
2023-05-30 16:12:37,036 - mineflayer - INFO - at e.message (/Users/willjiang/Desktop/web3dev/Voyager/voyager/env/mineflayer/node_modules/protodef/src/compiler.js:111:49)
2023-05-30 16:12:37,112 - mineflayer - INFO - PartialReadError: Read error for undefined : undefined
2023-05-30 16:12:37,112 - mineflayer - INFO - at new ExtendableError (/Users/willjiang/Desktop/web3dev/Voyager/voyager/env/mineflayer/node_modules/protodef/src/utils.js:63:13)
2023-05-30 16:12:37,112 - mineflayer - INFO - at new PartialReadError (/Users/willjiang/Desktop/web3dev/Voyager/voyager/env/mineflayer/node_modules/protodef/src/utils.js:70:5)
2023-05-30 16:12:37,112 - mineflayer - INFO - at Object.readVarInt [as varint] (/Users/willjiang/Desktop/web3dev/Voyager/voyager/env/mineflayer/node_modules/protodef/src/datatypes/utils.js:69:45)
2023-05-30 16:12:37,112 - mineflayer - INFO - at eval (eval at compile (/Users/willjiang/Desktop/web3dev/Voyager/voyager/env/mineflayer/node_modules/protodef/src/compiler.js:258:12), <anonymous>:241:59)
2023-05-30 16:12:37,112 - mineflayer - INFO - at Object.entityMetadata (eval at compile (/Users/willjiang/Desktop/web3dev/Voyager/voyager/env/mineflayer/node_modules/protodef/src/compiler.js:258:12), <anonymous>:244:9)
2023-05-30 16:12:37,112 - mineflayer - INFO - at Object.packet_entity_metadata (eval at compile (/Users/willjiang/Desktop/web3dev/Voyager/voyager/env/mineflayer/node_modules/protodef/src/compiler.js:258:12), <anonymous>:1778:73)
2023-05-30 16:12:37,112 - mineflayer - INFO - at eval (eval at compile (/Users/willjiang/Desktop/web3dev/Voyager/voyager/env/mineflayer/node_modules/protodef/src/compiler.js:258:12), <anonymous>:2398:70)
2023-05-30 16:12:37,112 - mineflayer - INFO - at packet (eval at compile (/Users/willjiang/Desktop/web3dev/Voyager/voyager/env/mineflayer/node_modules/protodef/src/compiler.js:258:12), <anonymous>:2428:9)
2023-05-30 16:12:37,112 - mineflayer - INFO - at CompiledProtodef.read (/Users/willjiang/Desktop/web3dev/Voyager/voyager/env/mineflayer/node_modules/protodef/src/compiler.js:70:12)
2023-05-30 16:12:37,112 - mineflayer - INFO - at e.message (/Users/willjiang/Desktop/web3dev/Voyager/voyager/env/mineflayer/node_modules/protodef/src/compiler.js:111:49)
2023-05-30 16:12:37,113 - mineflayer - INFO - PartialReadError: Read error for undefined : undefined
2023-05-30 16:12:37,113 - mineflayer - INFO - at new ExtendableError (/Users/willjiang/Desktop/web3dev/Voyager/voyager/env/mineflayer/node_modules/protodef/src/utils.js:63:13)
2023-05-30 16:12:37,113 - mineflayer - INFO - at new PartialReadError (/Users/willjiang/Desktop/web3dev/Voyager/voyager/env/mineflayer/node_modules/protodef/src/utils.js:70:5)
2023-05-30 16:12:37,113 - mineflayer - INFO - at Object.readVarInt [as varint] (/Users/willjiang/Desktop/web3dev/Voyager/voyager/env/mineflayer/node_modules/protodef/src/datatypes/utils.js:69:45)
2023-05-30 16:12:37,113 - mineflayer - INFO - at eval (eval at compile (/Users/willjiang/Desktop/web3dev/Voyager/voyager/env/mineflayer/node_modules/protodef/src/compiler.js:258:12), <anonymous>:241:59)
2023-05-30 16:12:37,113 - mineflayer - INFO - at Object.entityMetadata (eval at compile (/Users/willjiang/Desktop/web3dev/Voyager/voyager/env/mineflayer/node_modules/protodef/src/compiler.js:258:12), <anonymous>:244:9)
2023-05-30 16:12:37,113 - mineflayer - INFO - at Object.packet_entity_metadata (eval at compile (/Users/willjiang/Desktop/web3dev/Voyager/voyager/env/mineflayer/node_modules/protodef/src/compiler.js:258:12), <anonymous>:1778:73)
2023-05-30 16:12:37,113 - mineflayer - INFO - at eval (eval at compile (/Users/willjiang/Desktop/web3dev/Voyager/voyager/env/mineflayer/node_modules/protodef/src/compiler.js:258:12), <anonymous>:2398:70)
2023-05-30 16:12:37,113 - mineflayer - INFO - at packet (eval at compile (/Users/willjiang/Desktop/web3dev/Voyager/voyager/env/mineflayer/node_modules/protodef/src/compiler.js:258:12), <anonymous>:2428:9)
2023-05-30 16:12:37,113 - mineflayer - INFO - at CompiledProtodef.read (/Users/willjiang/Desktop/web3dev/Voyager/voyager/env/mineflayer/node_modules/protodef/src/compiler.js:70:12)
2023-05-30 16:12:37,113 - mineflayer - INFO - at e.message (/Users/willjiang/Desktop/web3dev/Voyager/voyager/env/mineflayer/node_modules/protodef/src/compiler.js:111:49)
2023-05-30 16:12:37,113 - mineflayer - INFO - PartialReadError: Read error for undefined : undefined
2023-05-30 16:12:37,113 - mineflayer - INFO - at new ExtendableError (/Users/willjiang/Desktop/web3dev/Voyager/voyager/env/mineflayer/node_modules/protodef/src/utils.js:63:13)
2023-05-30 16:12:37,113 - mineflayer - INFO - at new PartialReadError (/Users/willjiang/Desktop/web3dev/Voyager/voyager/env/mineflayer/node_modules/protodef/src/utils.js:70:5)
2023-05-30 16:12:37,113 - mineflayer - INFO - at Object.readVarInt [as varint] (/Users/willjiang/Desktop/web3dev/Voyager/voyager/env/mineflayer/node_modules/protodef/src/datatypes/utils.js:69:45)
2023-05-30 16:12:37,113 - mineflayer - INFO - at eval (eval at compile (/Users/willjiang/Desktop/web3dev/Voyager/voyager/env/mineflayer/node_modules/protodef/src/compiler.js:258:12), <anonymous>:241:59)
2023-05-30 16:12:37,113 - mineflayer - INFO - at Object.entityMetadata (eval at compile (/Users/willjiang/Desktop/web3dev/Voyager/voyager/env/mineflayer/node_modules/protodef/src/compiler.js:258:12), <anonymous>:244:9)
2023-05-30 16:12:37,113 - mineflayer - INFO - at Object.packet_entity_metadata (eval at compile (/Users/willjiang/Desktop/web3dev/Voyager/voyager/env/mineflayer/node_modules/protodef/src/compiler.js:258:12), <anonymous>:1778:73)
2023-05-30 16:12:37,113 - mineflayer - INFO - at eval (eval at compile (/Users/willjiang/Desktop/web3dev/Voyager/voyager/env/mineflayer/node_modules/protodef/src/compiler.js:258:12), <anonymous>:2398:70)
2023-05-30 16:12:37,113 - mineflayer - INFO - at packet (eval at compile (/Users/willjiang/Desktop/web3dev/Voyager/voyager/env/mineflayer/node_modules/protodef/src/compiler.js:258:12), <anonymous>:2428:9)
2023-05-30 16:12:37,113 - mineflayer - INFO - at CompiledProtodef.read (/Users/willjiang/Desktop/web3dev/Voyager/voyager/env/mineflayer/node_modules/protodef/src/compiler.js:70:12)
2023-05-30 16:12:37,113 - mineflayer - INFO - at e.message (/Users/willjiang/Desktop/web3dev/Voyager/voyager/env/mineflayer/node_modules/protodef/src/compiler.js:111:49)
2023-05-30 16:12:37,261 - mineflayer - INFO - PartialReadError: Read error for undefined : undefined
2023-05-30 16:12:37,261 - mineflayer - INFO - at new ExtendableError (/Users/willjiang/Desktop/web3dev/Voyager/voyager/env/mineflayer/node_modules/protodef/src/utils.js:63:13)
2023-05-30 16:12:37,262 - mineflayer - INFO - at new PartialReadError (/Users/willjiang/Desktop/web3dev/Voyager/voyager/env/mineflayer/node_modules/protodef/src/utils.js:70:5)
2023-05-30 16:12:37,262 - mineflayer - INFO - at Object.readVarInt [as varint] (/Users/willjiang/Desktop/web3dev/Voyager/voyager/env/mineflayer/node_modules/protodef/src/datatypes/utils.js:69:45)
2023-05-30 16:12:37,262 - mineflayer - INFO - at eval (eval at compile (/Users/willjiang/Desktop/web3dev/Voyager/voyager/env/mineflayer/node_modules/protodef/src/compiler.js:258:12), <anonymous>:241:59)
2023-05-30 16:12:37,262 - mineflayer - INFO - at Object.entityMetadata (eval at compile (/Users/willjiang/Desktop/web3dev/Voyager/voyager/env/mineflayer/node_modules/protodef/src/compiler.js:258:12), <anonymous>:244:9)
2023-05-30 16:12:37,262 - mineflayer - INFO - at Object.packet_entity_metadata (eval at compile (/Users/willjiang/Desktop/web3dev/Voyager/voyager/env/mineflayer/node_modules/protodef/src/compiler.js:258:12), <anonymous>:1778:73)
2023-05-30 16:12:37,262 - mineflayer - INFO - at eval (eval at compile (/Users/willjiang/Desktop/web3dev/Voyager/voyager/env/mineflayer/node_modules/protodef/src/compiler.js:258:12), <anonymous>:2398:70)
2023-05-30 16:12:37,262 - mineflayer - INFO - at packet (eval at compile (/Users/willjiang/Desktop/web3dev/Voyager/voyager/env/mineflayer/node_modules/protodef/src/compiler.js:258:12), <anonymous>:2428:9)
2023-05-30 16:12:37,262 - mineflayer - INFO - at CompiledProtodef.read (/Users/willjiang/Desktop/web3dev/Voyager/voyager/env/mineflayer/node_modules/protodef/src/compiler.js:70:12)
2023-05-30 16:12:37,262 - mineflayer - INFO - at e.message (/Users/willjiang/Desktop/web3dev/Voyager/voyager/env/mineflayer/node_modules/protodef/src/compiler.js:111:49)
2023-05-30 16:12:37,262 - mineflayer - INFO - PartialReadError: Read error for undefined : undefined
2023-05-30 16:12:37,262 - mineflayer - INFO - at new ExtendableError (/Users/willjiang/Desktop/web3dev/Voyager/voyager/env/mineflayer/node_modules/protodef/src/utils.js:63:13)
2023-05-30 16:12:37,262 - mineflayer - INFO - at new PartialReadError (/Users/willjiang/Desktop/web3dev/Voyager/voyager/env/mineflayer/node_modules/protodef/src/utils.js:70:5)
2023-05-30 16:12:37,262 - mineflayer - INFO - at Object.readVarInt [as varint] (/Users/willjiang/Desktop/web3dev/Voyager/voyager/env/mineflayer/node_modules/protodef/src/datatypes/utils.js:69:45)
2023-05-30 16:12:37,262 - mineflayer - INFO - at eval (eval at compile (/Users/willjiang/Desktop/web3dev/Voyager/voyager/env/mineflayer/node_modules/protodef/src/compiler.js:258:12), <anonymous>:241:59)
2023-05-30 16:12:37,262 - mineflayer - INFO - at Object.entityMetadata (eval at compile (/Users/willjiang/Desktop/web3dev/Voyager/voyager/env/mineflayer/node_modules/protodef/src/compiler.js:258:12), <anonymous>:244:9)
2023-05-30 16:12:37,262 - mineflayer - INFO - at Object.packet_entity_metadata (eval at compile (/Users/willjiang/Desktop/web3dev/Voyager/voyager/env/mineflayer/node_modules/protodef/src/compiler.js:258:12), <anonymous>:1778:73)
2023-05-30 16:12:37,262 - mineflayer - INFO - at eval (eval at compile (/Users/willjiang/Desktop/web3dev/Voyager/voyager/env/mineflayer/node_modules/protodef/src/compiler.js:258:12), <anonymous>:2398:70)
2023-05-30 16:12:37,262 - mineflayer - INFO - at packet (eval at compile (/Users/willjiang/Desktop/web3dev/Voyager/voyager/env/mineflayer/node_modules/protodef/src/compiler.js:258:12), <anonymous>:2428:9)
2023-05-30 16:12:37,262 - mineflayer - INFO - at CompiledProtodef.read (/Users/willjiang/Desktop/web3dev/Voyager/voyager/env/mineflayer/node_modules/protodef/src/compiler.js:70:12)
2023-05-30 16:12:37,262 - mineflayer - INFO - at e.message (/Users/willjiang/Desktop/web3dev/Voyager/voyager/env/mineflayer/node_modules/protodef/src/compiler.js:111:49)
2023-05-30 16:12:37,292 - mineflayer - INFO - PartialReadError: Read error for undefined : undefined
2023-05-30 16:12:37,292 - mineflayer - INFO - at new ExtendableError (/Users/willjiang/Desktop/web3dev/Voyager/voyager/env/mineflayer/node_modules/protodef/src/utils.js:63:13)
2023-05-30 16:12:37,292 - mineflayer - INFO - at new PartialReadError (/Users/willjiang/Desktop/web3dev/Voyager/voyager/env/mineflayer/node_modules/protodef/src/utils.js:70:5)
2023-05-30 16:12:37,292 - mineflayer - INFO - at Object.readVarInt [as varint] (/Users/willjiang/Desktop/web3dev/Voyager/voyager/env/mineflayer/node_modules/protodef/src/datatypes/utils.js:69:45)
2023-05-30 16:12:37,292 - mineflayer - INFO - at eval (eval at compile (/Users/willjiang/Desktop/web3dev/Voyager/voyager/env/mineflayer/node_modules/protodef/src/compiler.js:258:12), <anonymous>:241:59)
2023-05-30 16:12:37,292 - mineflayer - INFO - at Object.entityMetadata (eval at compile (/Users/willjiang/Desktop/web3dev/Voyager/voyager/env/mineflayer/node_modules/protodef/src/compiler.js:258:12), <anonymous>:244:9)
2023-05-30 16:12:37,292 - mineflayer - INFO - at Object.packet_entity_metadata (eval at compile (/Users/willjiang/Desktop/web3dev/Voyager/voyager/env/mineflayer/node_modules/protodef/src/compiler.js:258:12), <anonymous>:1778:73)
2023-05-30 16:12:37,292 - mineflayer - INFO - at eval (eval at compile (/Users/willjiang/Desktop/web3dev/Voyager/voyager/env/mineflayer/node_modules/protodef/src/compiler.js:258:12), <anonymous>:2398:70)
2023-05-30 16:12:37,292 - mineflayer - INFO - at packet (eval at compile (/Users/willjiang/Desktop/web3dev/Voyager/voyager/env/mineflayer/node_modules/protodef/src/compiler.js:258:12), <anonymous>:2428:9)
2023-05-30 16:12:37,292 - mineflayer - INFO - at CompiledProtodef.read (/Users/willjiang/Desktop/web3dev/Voyager/voyager/env/mineflayer/node_modules/protodef/src/compiler.js:70:12)
2023-05-30 16:12:37,292 - mineflayer - INFO - at e.message (/Users/willjiang/Desktop/web3dev/Voyager/voyager/env/mineflayer/node_modules/protodef/src/compiler.js:111:49)
2023-05-30 16:12:37,292 - mineflayer - INFO - PartialReadError: Read error for undefined : undefined
2023-05-30 16:12:37,292 - mineflayer - INFO - at new ExtendableError (/Users/willjiang/Desktop/web3dev/Voyager/voyager/env/mineflayer/node_modules/protodef/src/utils.js:63:13)
2023-05-30 16:12:37,292 - mineflayer - INFO - at new PartialReadError (/Users/willjiang/Desktop/web3dev/Voyager/voyager/env/mineflayer/node_modules/protodef/src/utils.js:70:5)
2023-05-30 16:12:37,292 - mineflayer - INFO - at Object.readVarInt [as varint] (/Users/willjiang/Desktop/web3dev/Voyager/voyager/env/mineflayer/node_modules/protodef/src/datatypes/utils.js:69:45)
2023-05-30 16:12:37,292 - mineflayer - INFO - at eval (eval at compile (/Users/willjiang/Desktop/web3dev/Voyager/voyager/env/mineflayer/node_modules/protodef/src/compiler.js:258:12), <anonymous>:241:59)
2023-05-30 16:12:37,292 - mineflayer - INFO - at Object.entityMetadata (eval at compile (/Users/willjiang/Desktop/web3dev/Voyager/voyager/env/mineflayer/node_modules/protodef/src/compiler.js:258:12), <anonymous>:244:9)
2023-05-30 16:12:37,292 - mineflayer - INFO - at Object.packet_entity_metadata (eval at compile (/Users/willjiang/Desktop/web3dev/Voyager/voyager/env/mineflayer/node_modules/protodef/src/compiler.js:258:12), <anonymous>:1778:73)
2023-05-30 16:12:37,292 - mineflayer - INFO - at eval (eval at compile (/Users/willjiang/Desktop/web3dev/Voyager/voyager/env/mineflayer/node_modules/protodef/src/compiler.js:258:12), <anonymous>:2398:70)
2023-05-30 16:12:37,292 - mineflayer - INFO - at packet (eval at compile (/Users/willjiang/Desktop/web3dev/Voyager/voyager/env/mineflayer/node_modules/protodef/src/compiler.js:258:12), <anonymous>:2428:9)
2023-05-30 16:12:37,292 - mineflayer - INFO - at CompiledProtodef.read (/Users/willjiang/Desktop/web3dev/Voyager/voyager/env/mineflayer/node_modules/protodef/src/compiler.js:70:12)
2023-05-30 16:12:37,292 - mineflayer - INFO - at e.message (/Users/willjiang/Desktop/web3dev/Voyager/voyager/env/mineflayer/node_modules/protodef/src/compiler.js:111:49)
2023-05-30 16:12:37,510 - mineflayer - INFO - node:internal/modules/cjs/loader:419
2023-05-30 16:12:37,510 - mineflayer - INFO - const err = new Error(
2023-05-30 16:12:37,510 - mineflayer - INFO - ^
2023-05-30 16:12:37,510 - mineflayer - INFO - 
2023-05-30 16:12:37,510 - mineflayer - INFO - Error: Cannot find module '/Users/willjiang/Desktop/web3dev/Voyager/voyager/env/mineflayer/node_modules/mineflayer-collectblock/lib/index.js'. Please verify that the package.json has a valid "main" entry
2023-05-30 16:12:37,510 - mineflayer - INFO - at tryPackage (node:internal/modules/cjs/loader:419:19)
2023-05-30 16:12:37,510 - mineflayer - INFO - at Module._findPath (node:internal/modules/cjs/loader:663:18)
2023-05-30 16:12:37,510 - mineflayer - INFO - at Module._resolveFilename (node:internal/modules/cjs/loader:1046:27)
2023-05-30 16:12:37,510 - mineflayer - INFO - at Module._load (node:internal/modules/cjs/loader:905:27)
2023-05-30 16:12:37,510 - mineflayer - INFO - at Module.require (node:internal/modules/cjs/loader:1127:19)
2023-05-30 16:12:37,510 - mineflayer - INFO - at require (node:internal/modules/helpers:112:18)
2023-05-30 16:12:37,510 - mineflayer - INFO - at EventEmitter.<anonymous> (/Users/willjiang/Desktop/web3dev/Voyager/voyager/env/mineflayer/index.js:100:30)
2023-05-30 16:12:37,510 - mineflayer - INFO - at Object.onceWrapper (node:events:626:28)
2023-05-30 16:12:37,510 - mineflayer - INFO - at EventEmitter.emit (node:events:524:35)
2023-05-30 16:12:37,510 - mineflayer - INFO - at Client.<anonymous> (/Users/willjiang/Desktop/web3dev/Voyager/voyager/env/mineflayer/node_modules/mineflayer/lib/plugins/health.js:13:11) {
2023-05-30 16:12:37,510 - mineflayer - INFO - code: 'MODULE_NOT_FOUND',
2023-05-30 16:12:37,510 - mineflayer - INFO - path: '/Users/willjiang/Desktop/web3dev/Voyager/voyager/env/mineflayer/node_modules/mineflayer-collectblock/package.json',
2023-05-30 16:12:37,510 - mineflayer - INFO - requestPath: 'mineflayer-collectblock'
2023-05-30 16:12:37,510 - mineflayer - INFO - }
2023-05-30 16:12:37,510 - mineflayer - INFO - 
2023-05-30 16:12:37,510 - mineflayer - INFO - Node.js v19.5.0
2023-05-30 16:12:37,552 - mineflayer - INFO - Stopping subprocess.`

**Comment by xieleo5** [comment]
Seems that `mineflayer-collectblock` is not installed correctly. You can try to reinstall it. 

Error: Cannot find module '/Users/willjiang/Desktop/web3dev/Voyager/voyager/env/mineflayer/node_modules/mineflayer-collectblock/lib/index.js'.
