### ISSUE TITLE
UserWarning: Subprocess mineflayer failed to start.

### ISSUE THREAD

**Issue by nehalgajraj** [MineDojo/Voyager#52]
Mineflayer process has exited, restarting
Subprocess mineflayer started with PID 37572.
Mineflayer process has exited, restarting
Subprocess mineflayer started with PID 6988.
Mineflayer process has exited, restarting
Subprocess mineflayer started with PID 38292.
Mineflayer process has exited, restarting
Subprocess mineflayer started with PID 33320.
Mineflayer process has exited, restarting
Subprocess mineflayer started with PID 17008.

and this runs on loop with different PID values....

What should I do?

**Comment by nehalgajraj** [comment]
`2023-05-31 16:12:50,152 - mineflayer - INFO - Stopping subprocess.
2023-05-31 16:12:51,162 - mineflayer - INFO - Starting subprocess with commands: ['node', 'C:\\Users\\nehal\\Desktop\\MineDojo\\Voyager\\voyager\\env\\mineflayer/index.js', '3000']
2023-05-31 16:12:51,209 - mineflayer - INFO - node:internal/modules/cjs/loader:1078
2023-05-31 16:12:51,209 - mineflayer - INFO - throw err;
2023-05-31 16:12:51,209 - mineflayer - INFO - ^
2023-05-31 16:12:51,209 - mineflayer - INFO - 
2023-05-31 16:12:51,209 - mineflayer - INFO - Error: Cannot find module 'express'
2023-05-31 16:12:51,209 - mineflayer - INFO - Require stack:
2023-05-31 16:12:51,220 - mineflayer - INFO - - C:\Users\nehal\Desktop\MineDojo\Voyager\voyager\env\mineflayer\index.js
2023-05-31 16:12:51,220 - mineflayer - INFO - at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
2023-05-31 16:12:51,220 - mineflayer - INFO - at Module._load (node:internal/modules/cjs/loader:920:27)
2023-05-31 16:12:51,220 - mineflayer - INFO - at Module.require (node:internal/modules/cjs/loader:1141:19)
2023-05-31 16:12:51,220 - mineflayer - INFO - at require (node:internal/modules/cjs/helpers:110:18)
2023-05-31 16:12:51,220 - mineflayer - INFO - at Object.<anonymous> (C:\Users\nehal\Desktop\MineDojo\Voyager\voyager\env\mineflayer\index.js:2:17)
2023-05-31 16:12:51,220 - mineflayer - INFO - at Module._compile (node:internal/modules/cjs/loader:1254:14)
2023-05-31 16:12:51,221 - mineflayer - INFO - at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
2023-05-31 16:12:51,221 - mineflayer - INFO - at Module.load (node:internal/modules/cjs/loader:1117:32)
2023-05-31 16:12:51,221 - mineflayer - INFO - at Module._load (node:internal/modules/cjs/loader:958:12)
2023-05-31 16:12:51,221 - mineflayer - INFO - at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
2023-05-31 16:12:51,221 - mineflayer - INFO - code: 'MODULE_NOT_FOUND',
2023-05-31 16:12:51,221 - mineflayer - INFO - requireStack: [
2023-05-31 16:12:51,221 - mineflayer - INFO - 'C:\\Users\\nehal\\Desktop\\MineDojo\\Voyager\\voyager\\env\\mineflayer\\index.js'
2023-05-31 16:12:51,221 - mineflayer - INFO - ]
2023-05-31 16:12:51,221 - mineflayer - INFO - }
2023-05-31 16:12:51,221 - mineflayer - INFO - 
2023-05-31 16:12:51,221 - mineflayer - INFO - Node.js v18.15.0
2023-05-31 16:12:51,237 - mineflayer - INFO - Starting subprocess with commands: ['node', 'C:\\Users\\nehal\\Desktop\\MineDojo\\Voyager\\voyager\\env\\mineflayer/index.js', '3000']
2023-05-31 16:12:51,287 - mineflayer - INFO - node:internal/modules/cjs/loader:1078
2023-05-31 16:12:51,287 - mineflayer - INFO - throw err;
2023-05-31 16:12:51,287 - mineflayer - INFO - ^
2023-05-31 16:12:51,287 - mineflayer - INFO - 
2023-05-31 16:12:51,287 - mineflayer - INFO - Error: Cannot find module 'express'
2023-05-31 16:12:51,287 - mineflayer - INFO - Require stack:
2023-05-31 16:12:51,287 - mineflayer - INFO - - C:\Users\nehal\Desktop\MineDojo\Voyager\voyager\env\mineflayer\index.js
2023-05-31 16:12:51,287 - mineflayer - INFO - at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
2023-05-31 16:12:51,287 - mineflayer - INFO - at Module._load (node:internal/modules/cjs/loader:920:27)
2023-05-31 16:12:51,287 - mineflayer - INFO - at Module.require (node:internal/modules/cjs/loader:1141:19)
2023-05-31 16:12:51,287 - mineflayer - INFO - at require (node:internal/modules/cjs/helpers:110:18)
2023-05-31 16:12:51,287 - mineflayer - INFO - at Object.<anonymous> (C:\Users\nehal\Desktop\MineDojo\Voyager\voyager\env\mineflayer\index.js:2:17)
2023-05-31 16:12:51,287 - mineflayer - INFO - at Module._compile (node:internal/modules/cjs/loader:1254:14)
2023-05-31 16:12:51,287 - mineflayer - INFO - at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
2023-05-31 16:12:51,287 - mineflayer - INFO - at Module.load (node:internal/modules/cjs/loader:1117:32)
2023-05-31 16:12:51,287 - mineflayer - INFO - at Module._load (node:internal/modules/cjs/loader:958:12)
2023-05-31 16:12:51,287 - mineflayer - INFO - at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
2023-05-31 16:12:51,287 - mineflayer - INFO - code: 'MODULE_NOT_FOUND',
2023-05-31 16:12:51,287 - mineflayer - INFO - requireStack: [
2023-05-31 16:12:51,287 - mineflayer - INFO - 'C:\\Users\\nehal\\Desktop\\MineDojo\\Voyager\\voyager\\env\\mineflayer\\index.js'
2023-05-31 16:12:51,287 - mineflayer - INFO - ]
2023-05-31 16:12:51,287 - mineflayer - INFO - }
2023-05-31 16:12:51,287 - mineflayer - INFO - 
2023-05-31 16:12:51,287 - mineflayer - INFO - Node.js v18.15.0
2023-05-31 16:12:51,305 - mineflayer - INFO - Starting subprocess with commands: ['node', 'C:\\Users\\nehal\\Desktop\\MineDojo\\Voyager\\voyager\\env\\mineflayer/index.js', '3000']
2023-05-31 16:12:51,353 - mineflayer - INFO - node:internal/modules/cjs/loader:1078
2023-05-31 16:12:51,353 - mineflayer - INFO - throw err;
2023-05-31 16:12:51,353 - mineflayer - INFO - ^
2023-05-31 16:12:51,353 - mineflayer - INFO - 
2023-05-31 16:12:51,354 - mineflayer - INFO - Error: Cannot find module 'express'
2023-05-31 16:12:51,354 - mineflayer - INFO - Require stack:
2023-05-31 16:12:51,354 - mineflayer - INFO - - C:\Users\nehal\Desktop\MineDojo\Voyager\voyager\env\mineflayer\index.js
2023-05-31 16:12:51,354 - mineflayer - INFO - at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
2023-05-31 16:12:51,354 - mineflayer - INFO - at Module._load (node:internal/modules/cjs/loader:920:27)
2023-05-31 16:12:51,354 - mineflayer - INFO - at Module.require (node:internal/modules/cjs/loader:1141:19)`

**Comment by nehalgajraj** [comment]
2023-05-31 16:12:50,152 - mineflayer - INFO - Stopping subprocess.
2023-05-31 16:12:51,162 - mineflayer - INFO - Starting subprocess with commands: ['node', 'C:\\Users\\nehal\\Desktop\\MineDojo\\Voyager\\voyager\\env\\mineflayer/index.js', '3000']
2023-05-31 16:12:51,209 - mineflayer - INFO - node:internal/modules/cjs/loader:1078
2023-05-31 16:12:51,209 - mineflayer - INFO - throw err;
2023-05-31 16:12:51,209 - mineflayer - INFO - ^
2023-05-31 16:12:51,209 - mineflayer - INFO - 
2023-05-31 16:12:51,209 - mineflayer - INFO - Error: Cannot find module 'express'
2023-05-31 16:12:51,209 - mineflayer - INFO - Require stack:
2023-05-31 16:12:51,220 - mineflayer - INFO - - C:\Users\nehal\Desktop\MineDojo\Voyager\voyager\env\mineflayer\index.js
2023-05-31 16:12:51,220 - mineflayer - INFO - at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
2023-05-31 16:12:51,220 - mineflayer - INFO - at Module._load (node:internal/modules/cjs/loader:920:27)
2023-05-31 16:12:51,220 - mineflayer - INFO - at Module.require (node:internal/modules/cjs/loader:1141:19)
2023-05-31 16:12:51,220 - mineflayer - INFO - at require (node:internal/modules/cjs/helpers:110:18)
2023-05-31 16:12:51,220 - mineflayer - INFO - at Object.<anonymous> (C:\Users\nehal\Desktop\MineDojo\Voyager\voyager\env\mineflayer\index.js:2:17)
2023-05-31 16:12:51,220 - mineflayer - INFO - at Module._compile (node:internal/modules/cjs/loader:1254:14)
2023-05-31 16:12:51,221 - mineflayer - INFO - at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
2023-05-31 16:12:51,221 - mineflayer - INFO - at Module.load (node:internal/modules/cjs/loader:1117:32)
2023-05-31 16:12:51,221 - mineflayer - INFO - at Module._load (node:internal/modules/cjs/loader:958:12)
2023-05-31 16:12:51,221 - mineflayer - INFO - at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
2023-05-31 16:12:51,221 - mineflayer - INFO - code: 'MODULE_NOT_FOUND',
2023-05-31 16:12:51,221 - mineflayer - INFO - requireStack: [
2023-05-31 16:12:51,221 - mineflayer - INFO - 'C:\\Users\\nehal\\Desktop\\MineDojo\\Voyager\\voyager\\env\\mineflayer\\index.js'
2023-05-31 16:12:51,221 - mineflayer - INFO - ]
2023-05-31 16:12:51,221 - mineflayer - INFO - }
2023-05-31 16:12:51,221 - mineflayer - INFO - 
2023-05-31 16:12:51,221 - mineflayer - INFO - Node.js v18.15.0
2023-05-31 16:12:51,237 - mineflayer - INFO - Starting subprocess with commands: ['node', 'C:\\Users\\nehal\\Desktop\\MineDojo\\Voyager\\voyager\\env\\mineflayer/index.js', '3000']
2023-05-31 16:12:51,287 - mineflayer - INFO - node:internal/modules/cjs/loader:1078
2023-05-31 16:12:51,287 - mineflayer - INFO - throw err;
2023-05-31 16:12:51,287 - mineflayer - INFO - ^
2023-05-31 16:12:51,287 - mineflayer - INFO - 
2023-05-31 16:12:51,287 - mineflayer - INFO - Error: Cannot find module 'express'
2023-05-31 16:12:51,287 - mineflayer - INFO - Require stack:
2023-05-31 16:12:51,287 - mineflayer - INFO - - C:\Users\nehal\Desktop\MineDojo\Voyager\voyager\env\mineflayer\index.js
2023-05-31 16:12:51,287 - mineflayer - INFO - at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
2023-05-31 16:12:51,287 - mineflayer - INFO - at Module._load (node:internal/modules/cjs/loader:920:27)
2023-05-31 16:12:51,287 - mineflayer - INFO - at Module.require (node:internal/modules/cjs/loader:1141:19)
2023-05-31 16:12:51,287 - mineflayer - INFO - at require (node:internal/modules/cjs/helpers:110:18)
2023-05-31 16:12:51,287 - mineflayer - INFO - at Object.<anonymous> (C:\Users\nehal\Desktop\MineDojo\Voyager\voyager\env\mineflayer\index.js:2:17)
2023-05-31 16:12:51,287 - mineflayer - INFO - at Module._compile (node:internal/modules/cjs/loader:1254:14)
2023-05-31 16:12:51,287 - mineflayer - INFO - at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
2023-05-31 16:12:51,287 - mineflayer - INFO - at Module.load (node:internal/modules/cjs/loader:1117:32)
2023-05-31 16:12:51,287 - mineflayer - INFO - at Module._load (node:internal/modules/cjs/loader:958:12)
2023-05-31 16:12:51,287 - mineflayer - INFO - at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
2023-05-31 16:12:51,287 - mineflayer - INFO - code: 'MODULE_NOT_FOUND',
2023-05-31 16:12:51,287 - mineflayer - INFO - requireStack: [
2023-05-31 16:12:51,287 - mineflayer - INFO - 'C:\\Users\\nehal\\Desktop\\MineDojo\\Voyager\\voyager\\env\\mineflayer\\index.js'
2023-05-31 16:12:51,287 - mineflayer - INFO - ]
2023-05-31 16:12:51,287 - mineflayer - INFO - }
2023-05-31 16:12:51,287 - mineflayer - INFO - 
2023-05-31 16:12:51,287 - mineflayer - INFO - Node.js v18.15.0
2023-05-31 16:12:51,305 - mineflayer - INFO - Starting subprocess with commands: ['node', 'C:\\Users\\nehal\\Desktop\\MineDojo\\Voyager\\voyager\\env\\mineflayer/index.js', '3000']
2023-05-31 16:12:51,353 - mineflayer - INFO - node:internal/modules/cjs/loader:1078
2023-05-31 16:12:51,353 - mineflayer - INFO - throw err;
2023-05-31 16:12:51,353 - mineflayer - INFO - ^
2023-05-31 16:12:51,353 - mineflayer - INFO - 
2023-05-31 16:12:51,354 - mineflayer - INFO - Error: Cannot find module 'express'
2023-05-31 16:12:51,354 - mineflayer - INFO - Require stack:
2023-05-31 16:12:51,354 - mineflayer - INFO - - C:\Users\nehal\Desktop\MineDojo\Voyager\voyager\env\mineflayer\index.js
2023-05-31 16:12:51,354 - mineflayer - INFO - at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
2023-05-31 16:12:51,354 - mineflayer - INFO - at Module._load (node:internal/modules/cjs/loader:920:27)
2023-05-31 16:12:51,354 - mineflayer - INFO - at Module.require (node:internal/modules/cjs/loader:1141:19)

**Comment by xieleo5** [comment]
Seems that some of the node js packages are missing. Did you run `npm install`?

**Comment by nehalgajraj** [comment]
oh, I did not, my oversight. Thank you.
