### ISSUE TITLE
tonen access problem but now is 271 line

### ISSUE THREAD

**Issue by TheAdrianPOP** [MineDojo/Voyager#53]
C:\Users\ASUS>python C:\Users\ASUS\Voyager\AI_Minecraft.py
Creating Minecraft server
Please open https://login.microsoftonline.com/consumers/oauth2/v2.0/authorize?client_id=ab3074f2-1ea7-425a-8ace-96b0fe4ebf0d&response_type=code&redirect_uri=https%3A%2F%2F127.0.0.1%2Fauth-response&response_mode=query&scope=XboxLive.signin+offline_access&state=ABCxLmKy-FJZFdd7JDJ3Rg&code_challenge=Bvlys465ZivXQKua5QrxZqtOhFHvd_f03S0C43BMfhc&code_challenge_method=S256 in your browser and copy the url you are redirected into the prompt below.
https://127.0.0.1/auth-response?code=M.C103_BL2.2.32bbc6a8-8e19-9400-db2f-8dd6bcc9282f&state=ABCxLmKy-FJZFdd7JDJ3Rg
Traceback (most recent call last):
  File "C:\Users\ASUS\Voyager\AI_Minecraft.py", line 12, in <module>
    voyager = Voyager(
              ^^^^^^^^
  File "C:\Users\ASUS\Voyager\voyager\voyager.py", line 102, in __init__
    self.env = VoyagerEnv(
               ^^^^^^^^^^^
  File "C:\Users\ASUS\Voyager\voyager\env\bridge.py", line 42, in __init__
    self.mc_instance = self.get_mc_instance()
                       ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Voyager\voyager\env\bridge.py", line 67, in get_mc_instance
    return MinecraftInstance(
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Voyager\voyager\env\minecraft_launcher.py", line 36, in __init__
    self.mc_command = self.get_mc_command()
                      ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Voyager\voyager\env\minecraft_launcher.py", line 89, in get_mc_command
    login_data = minecraft_launcher_lib.microsoft_account.complete_login(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python311\site-packages\minecraft_launcher_lib\microsoft_account.py", line 271, in complete_login
    access_token = account_request["access_token"]
                   ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'access_token'

I don't think I fixed that .. line 271.. what this mean because I totally stuck in access_code

**Comment by changliucoding** [comment]
Have the same error
