### ISSUE TITLE
Error occurred when python install step in Installation

### ISSUE THREAD

**Issue by masa-ibara** [MineDojo/Voyager#62]
Error occurred when python install step in Installation.
I think it's based on the default language settings, but can you force it to utf-8?

```
pip install -e .
Obtaining file:///D:/GitRepository/Voyager
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... error
  error: subprocess-exited-with-error

  × Getting requirements to build editable did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "C:\Users\hoge\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\hoge\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\hoge\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 132, in get_requires_for_build_editable
          return hook(config_settings)
        File "C:\Users\hoge\AppData\Local\Temp\pip-build-env-o6hj_xgz\overlay\Lib\site-packages\setuptools\build_meta.py", line 450, in get_requires_for_build_editable
          return self.get_requires_for_build_wheel(config_settings)
        File "C:\Users\hoge\AppData\Local\Temp\pip-build-env-o6hj_xgz\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\hoge\AppData\Local\Temp\pip-build-env-o6hj_xgz\overlay\Lib\site-packages\setuptools\build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "C:\Users\hoge\AppData\Local\Temp\pip-build-env-o6hj_xgz\overlay\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup
          super(_BuildMetaLegacyBackend,
        File "C:\Users\hoge\AppData\Local\Temp\pip-build-env-o6hj_xgz\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 38, in <module>
        File "<string>", line 16, in _read_file
      UnicodeDecodeError: 'cp932' codec can't decode byte 0x97 in position 1767: illegal multibyte sequence
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error
```

**Comment by xieleo5** [comment]
Seems a similar issue as #8, can you try the solution mentioned there?
